# Generated by Django 2.1.3 on 2018-11-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_titulo', models.CharField(choices=[('I', 'IPCA+'), ('S', 'Selic'), ('P', 'Prefixado'), ('IJS', 'IPCA+ com Juros Semestrais'), ('PJS', 'Prefixado com Juros Semestrais')], default=None, max_length=48)),
                ('data_vencimento', models.DateTimeField(default=None)),
                ('data_base', models.DateTimeField(default=None)),
                ('taxa_compra', models.FloatField(default=None)),
                ('taxa_venda', models.FloatField(default=None)),
                ('pu_compra', models.FloatField(default=None)),
                ('pu_venda', models.FloatField(default=None)),
                ('pu_base', models.FloatField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TituloAtivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_titulo', models.CharField(choices=[('I', 'IPCA+'), ('S', 'Selic'), ('P', 'Prefixado'), ('IJS', 'IPCA+ com Juros Semestrais'), ('PJS', 'Prefixado com Juros Semestrais')], default=None, max_length=48)),
                ('data_vencimento', models.DateTimeField(default=None)),
                ('data_base', models.DateTimeField(default=None)),
                ('taxa_compra', models.FloatField(default=None)),
                ('taxa_venda', models.FloatField(default=None)),
                ('pu_compra', models.FloatField(default=None)),
                ('pu_venda', models.FloatField(default=None)),
                ('pu_base', models.FloatField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='tituloativo',
            unique_together={('tipo_titulo', 'data_vencimento', 'data_base')},
        ),
        migrations.AlterUniqueTogether(
            name='titulo',
            unique_together={('tipo_titulo', 'data_vencimento', 'data_base')},
        ),
    ]
