# Generated by Django 2.1.3 on 2018-11-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tituloativo',
            name='opcao',
            field=models.CharField(choices=[('C', 'compra'), ('V', 'venda')], default=None, max_length=16),
        ),
    ]
