# Generated by Django 2.1.3 on 2018-11-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stn', '0002_tituloativo_opcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='pu_base',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='pu_compra',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='pu_venda',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='taxa_compra',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='taxa_venda',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tituloativo',
            name='pu_base',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tituloativo',
            name='pu_compra',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tituloativo',
            name='pu_venda',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tituloativo',
            name='taxa_compra',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tituloativo',
            name='taxa_venda',
            field=models.FloatField(default=None, null=True),
        ),
    ]
